### ISSUE TITLE
Explore using gorm hooks to update row meta data

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-commander#110]
We want to use [hooks](https://gorm.io/docs/hooks.html) to update the tree metadata like `type`, `level` and so on.

**Comment by ChihChengLiang** [comment]
I would argue that we should remove the Type and Level columns. `Path` already encoded those two pieces of information, it is what we need to store only.

**Comment by vaibhavchellani** [comment]
Yeah, `type` and `level` are just metadata that helps in better querying for multiple functions. The upside is great and downside is just some metadata storage and maintenance which isn't too bad. 

Feel free to reopen I think I am okay with the current way of handling these fields.
