### ISSUE TITLE
Abstract away routes from start script

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-commander#20]
We have a hacky way of defining routes atm need to abstract them out and have a better way to add/remove them. 
Current dirty implementation: https://github.com/thehubbleproject/hubble-commander/blob/master/cmd/start.go#L84-L86

**Comment by vaibhavchellani** [comment]
@ChihChengLiang would you be interested in taking this up as the first issue?

**Comment by ChihChengLiang** [comment]
Happy to work on this.
