### ISSUE TITLE
Create tree abstraction

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-commander#27]
We manage 2 trees on our DB, `accounts tree` and `states tree` which have a lot of common API's for example `GetAccountByPath`, `GetStateByDepth` and other such functions. It seems quite obvious that we should spend some time creating an abstract tree that account and state can utilize to avoid a ton of code maintenance and duplication

**Comment by ChihChengLiang** [comment]
Close in favor of #84
