### ISSUE TITLE
Add encoders/decoders for more txs

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-commander#30]
https://github.com/thehubbleproject/hubble-commander/blob/master/core/bazooka.go#L220

**Comment by vaibhavchellani** [comment]
Correct link: https://github.com/thehubbleproject/hubble-commander/blob/master/core/bazooka.go#L306

**Comment by ChihChengLiang** [comment]
We are talking about adding encoders/decoders for Create2Transfer and MassMigration here.
