### ISSUE TITLE
Add API's for wallet

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/hubble-commander#36]
We need to add API's for the following tasks
- Send tx
- View tx status
- View tx details

**Comment by barryWhiteHat** [comment]
Would it be a good idea to implement the geth RPC api in our node. That way wallets can just use ethers.js with our node as endpoint. There will be some calls that don't make sense that we can just return garbage for. 

Seems like if we get every rollup node talking the same language we can easily build block exploerers and wallets to interact with them.

**Comment by vaibhavchellani** [comment]
That would be the dream indeed, let me create another issue for that. This one would target API's needed short term for BLS burner wallet to work.

**Comment by vaibhavchellani** [comment]
Done!
