### ISSUE TITLE
Create a NewWallet constructor that takes domain

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-commander#72]
### What's wrong

The current NewWallet constructor uses a dummy default domain for BLS signer. This won't work with the actual production contracts. The rollup contract defines a [domain](https://github.com/thehubbleproject/hubble-contracts/blob/master/contracts/rollup/Rollup.sol#L247), which is named APP_ID and is the hash of rollup contract's address, that all signatures validation should agree to.
Any signature signed with an incorrect domain will be considered invalid by the contract.

### How can we fix it

- NewWallet constructor takes the domain bytes as an argument.
- Pass correct domain, i.e. the hash of rollup contract's address, to the constructors of the signers and verifiers everywhere.

**Comment by vaibhavchellani** [comment]
Think this is fixed now, feel free to reopen!
