### ISSUE TITLE
Merkle Tree abstraction

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/hubble-commander#84]
### What's wrong

In Hubble, we have two huge Merkle trees to build: The account tree and the user state tree. We have two main problems:

1. Code duplications for the same logics. The `account.go` and `state.go` looks almost the same. This motivates abstraction.
2. Performance. We currently store all tree nodes in the database, and we have to populate the whole tree in DB at the initialization of the client. This would be a problem when we have a tree depth of 32, which means we'll need to write 2**33 nodes in DB.

### How can we fix this

Proposing abstraction

- Having a tree interface, that has a Get and Update method. `Get` gets a piece of data with its witness, and Update updates the paths back to DB.
- Having a common `Node` Model, but we keep a separate "UserState" table and "Account" table for state's and account's tree nodes.
- Having default hashes in memory, so we don't need to populate the whole tree at the start. We get a node from DB if the subtree is filled, and a node from the default hashes if the subtree is empty

**Comment by vaibhavchellani** [comment]
Closing, for now, to be dealt with later
